<?xml version="1.0" encoding="UTF-8"?>
<testsuite time="[mock]" timestamp="[mock]" tests="2" skipped="0" failures="2">
  <testcase
    file="error_in_test_function.spec.js"
    name="worker_thread"
    time="[mock]"
    timestamp="[mock]"
    tests="1"
    errors="1"
  >
    <properties>
      <property name="runtimeName" value="node_worker_thread"></property>
      <property name="runtimeVersion" value="20.8.0"></property>
    </properties>
  </testcase>
  <error type="Error">1 | const getCircle = () =&#x3E; {
2 |   throw new Error(&#x22;circle&#x22;);
            ^
Error: circle
  at getCircle ([mock]/error_in_test_function.spec.js:2:9)
  at [mock]/error_in_test_function.spec.js:5:1</error>
  <testcase
    file="error_in_test_function.spec.js"
    name="child_process"
    time="[mock]"
    timestamp="[mock]"
    tests="1"
    errors="1"
  >
    <properties>
      <property name="runtimeName" value="node_child_process"></property>
      <property name="runtimeVersion" value="20.8.0"></property>
    </properties>
  </testcase>
  <error type="Error">1 | const getCircle = () =&#x3E; {
2 |   throw new Error(&#x22;circle&#x22;);
            ^
Error: circle
  at getCircle ([mock]/error_in_test_function.spec.js:2:9)
  at [mock]/error_in_test_function.spec.js:5:1</error>
</testsuite>